[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn app_3:app --host 0.0.0.0 --port $PORT"
numReplicas = 1
healthCheckPath = "/health"
healthCheckTimeout = 200
sleepApplication= false
restarPolicyType = "ON_FAILURE"
restarPolicyMaxRetries = 1

